version: '2'
services:
  notebook:
    container_name: busbud-notebook
    image: busbud-notebook
    tty: true
    ports:
      - 8888:8888
    volumes:
      - ${NOTEBOOKS_DIR}:/notebooks
      - ${HOST_PACKAGES_DIR}:/host-packages
    environment:
      SQL_DATABASE_URI: 'postgres://user@host:1234/database'
      ANOTHER_SQL_DATABASE_URI: 'postgres://user@host:1234/database'
      BIGDATA_BQ_PROJECT: 'big-data'
      BIGDATA_BQ_EMAIL: 'foobar@developer.gserviceaccount.com'
      BIGDATA_BQ_KEY: |
          -----BEGIN PRIVATE KEY-----
          -----END PRIVATE KEY-----
